# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ec243d8056c7e70c3b99903a2d81e741863eba2f90f6d7f7deec7662c931a11aba402a8333e80a049100f416115cd6b547ca3c1e02ea74eae1eaa37ff12ee9

test:
  secret_key_base: dbcb9749fe237525307a7ca9a26c5cfdffecda8ca8348a61da13621b8160f0fef48821814dd06bbfb7d3b3d068e09701fa44838f6144e7839121aab91a021253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
